### ISSUE TITLE
Uncaught Error: Bootstrap requires jQuery

### ISSUE THREAD

**Issue by Suzanskiy** [Sonya-SV/BeautySalonSpring#1]
There is only white screen. How can i repair that? Please help me, i'll appreciate your project!
![image](https://user-images.githubusercontent.com/18307543/70607417-14f26480-1c07-11ea-9612-bdb800bed947.png)

**Comment by Sonya-SV** [comment]
Nothing should be there, it's just a start page. But to remove the error,
you need to delete or  the line in the file:  /resources / templates /
common / parts / common.ftl , line 14.
<script src = "
https://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js">
The link is not used anymore, but I forgot to delete.

ср, 11 груд. 2019 о 11:12 Suzanskiy <notifications@github.com> пише:

**Comment by Suzanskiy** [comment]
Thank you, it work .But how can i add any master's photo? There is png/base64 photo type. 
![image](https://user-images.githubusercontent.com/18307543/70616194-8c7bc000-1c16-11ea-8a21-577facac49df.png)

**Comment by Sonya-SV** [comment]
I did not implement the method of adding a master in the application.
The photo is pulled from the database, where I manually added a file. You
just need to upload a picture to database and it will be displayed.

ср, 11 груд. 2019 о 13:02 Suzanskiy <notifications@github.com> пише:

**Comment by Suzanskiy** [comment]
Я понял что вы знаете русский. Подскажите, пожалуйста, как добавить эту фотографию. Я как раз пробую через базу, но всё равно не выходит. Нужно вставлять урл на фото, или расположение в файловой системе? 
![image](https://user-images.githubusercontent.com/18307543/70619165-16c72280-1c1d-11ea-844f-d62ef922e603.png)

**Comment by Sonya-SV** [comment]
Тип поля, где хранится фотография - mediumblob.
Чтобы сохранить нужно нажать на поле -> Open value in Editor -> Load.
[image: image.png]

ср, 11 груд. 2019 о 13:49 Suzanskiy <notifications@github.com> пише:
